[package]
name = "perfume"
version = "0.3.2"
authors = ["Daniel James Baumann <dan.james.baumann@gmail.com>"]
description = "Impromptu conversion of sensitive metadata to persistent random names."
license = "MIT OR Apache-2.0"
repository = "https://github.com/guapodero/perfume"
keywords = ["privacy", "random", "generator"]
categories = ["authentication", "web-programming", "accessibility", "asynchronous"]
exclude = [".github", "data"]
edition = "2024"

[features]
codegen = ["phf_codegen"]
nightly = []

[dependencies]
rand = "0.10"
rand_chacha = "0.10"
cfg-if = "1"
blake3 = "1"
base16ct = "1"
thiserror = "2"
http = "1"
bytes = "1"
async-generic = "1"
phf = "0.14"

phf_codegen = { version = "0.14", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "test-util"] }
ureq = "3"
httparse = "1"
const_env = "0.1"
